apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-conf
data:
  nginx.conf: |
    user nginx;
      worker_processes  1;
      events {
        worker_connections  10240;
      }
      http {
        server {
            listen       80;
            server_name  localhost;
            location / {
              root   html;
              index  index.html index.htm;
            }
            location = /basic_status {
                stub_status;
                allow 127.0.0.1;
                deny all;
            }
        }
      }