apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  type: NodePort
  selector:
    app: nginx
  ports:
    - name: nginx-port
      protocol: TCP
      port: 8000
      targetPort: nginx
    - name: nginx-exporter-port
      protocol: TCP
      port: 9113
      nodePort: 31555
      targetPort: exporter
