apiVersion: v1
kind: Service
metadata:
  name: frontend
  labels:
    app: frontend
spec:
  type: {{ .Values.service.type | default "ClusterIP" }}
  selector:
    app: frontend
  ports:
    - name: frontend
      port: {{ .Values.service.port | default 80 }}
{{- if eq .Values.service.type "NodePort" }}
      nodePort: {{ .Values.service.nodePort | default 32080 }}
{{- end }}
      targetPort: {{ .Values.service.targetPort | default 8080 }}