apiVersion: v1
kind: Pod
metadata:
  name: web
  labels:
    app: web
spec:
  volumes:
    - name: app
      emptyDir: {}
  containers:
    - name: web
      image: zlayasova/web:1.0
      livenessProbe:
        tcpSocket: { port: 8000 }
      readinessProbe:
        httpGet:
          path: /index.html
          port: 80
      volumeMounts:
        - name: app
          mountPath: /app
  initContainers:
    - name: init-web
      image: busybox:1.36.0
      command: ['sh', '-c', 'wget -O- https://tinyurl.com/otus-k8s-intro | sh']
      volumeMounts:
        - name: app
          mountPath: /app
